# eIQ NXP Software framework for i.MX 8M Plus HMX1 Machine configuration

require conf/machine/imx8mp-var-dart-hmx1.conf

MACHINE_FEATURES:append:use-nxp-bsp = " optee jailhouse mrvl8997"

DEFAULTTUNE:mx8m-generic-bsp = "armv8a-crc-crypto"

IMAGE_INSTALL:remove:imx8mp-var-dart-hmx1 = ""
IMAGE_INSTALL:append:imx8mp-var-dart-hmx1 = " packagegroup-imx-isp"
